// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Rent & Radiate catalog for dresses or jewellery available to rent or buy. Filter by keywords, category, and max price.",
  inputSchema: {
    query: z.string().trim().max(120).optional().describe("Keywords to match in product title."),
    category: z.enum(["dress", "jewellery", "all"]).default("all"),
    purpose: z.enum(["rent", "buy", "all"]).default("all"),
    max_price: z.number().positive().optional().describe("Max selling price (INR)."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, purpose, max_price, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("products").select("id,title,category,purpose,price_per_day,actual_price,security_deposit,images,available").eq("available", true).limit(limit);
    if (query) q = q.ilike("title", `%${query}%`);
    if (category !== "all") q = q.eq("category", category);
    if (purpose !== "all") q = q.in("purpose", [purpose, "both"]);
    if (max_price) q = q.lte("actual_price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-rentals.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_rentals_default = defineTool2({
  name: "list_my_rentals",
  title: "List my rentals & orders",
  description: "List the signed-in user's rentals and purchase orders on Rent & Radiate, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20),
    status: z2.string().optional().describe("Optional rental status filter, e.g. pending, confirmed, shipped, delivered, returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("rentals").select(
      "id,kind,status,payment_status,grand_total,start_date,end_date,created_at,product_id,quantity"
    ).eq("customer_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rentals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-wishlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_wishlist_default = defineTool3({
  name: "list_my_wishlist",
  title: "List my wishlist",
  description: "List products the signed-in user has saved to their Rent & Radiate wishlist.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("wishlists").select("id,created_at,product_id,products(id,title,category,actual_price,price_per_day,images)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { wishlist: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-to-wishlist.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_to_wishlist_default = defineTool4({
  name: "add_to_wishlist",
  title: "Add to wishlist",
  description: "Save a product to the signed-in user's Rent & Radiate wishlist.",
  inputSchema: {
    product_id: z4.string().uuid().describe("The product UUID to save.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ product_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("wishlists").upsert(
      { user_id: ctx.getUserId(), product_id },
      { onConflict: "user_id,product_id", ignoreDuplicates: true }
    ).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Added to wishlist." }],
      structuredContent: { row: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zlyazcpuxzdvudrfzjxu";
var mcp_default = defineMcp({
  name: "rent-and-radiate-mcp",
  title: "Rent & Radiate",
  version: "0.1.0",
  instructions: "Tools for the Rent & Radiate fashion rental marketplace. Use search_products to browse dresses and jewellery. Use list_my_rentals, list_my_wishlist, and add_to_wishlist to act on behalf of the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, list_my_rentals_default, list_my_wishlist_default, add_to_wishlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
